### ISSUE TITLE
Fix error for styling compliation after update to Magento 2.2.6

### ISSUE THREAD

**Issue by mishanino** [magespecialist/m2-MSP_Security_Suite_Common#4]
After updating magento to 2.2.6 version, module caused the error in styling compilation for adminhtml backend theme 
![image- 1](https://user-images.githubusercontent.com/4930295/46150803-15a71100-c276-11e8-8e28-1bce1c01f93f.png)

**Comment by magefan** [comment]
The same issue. Also when we open the file

**Comment by magefan** [comment]
The same issue (Magento 2.2.2)
Also when we open the file
pub/static/adminhtml/Magento/backend/en_US/css/styles.css

we see this
```

 in _module.less on line 22, column 5
20) .msp_securitysuite-comment {
21)     padding-left: 60px;
22)     background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcfDykeHoMc6wAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAA4cSURBVGjexZp7sF1Vfcc/v7X2Pufcm5vcPG8wIUAaHrmJjKIwKhTFFl8zLRIebdWxUJ52BghFbNGqndppqwhSIEUSEx7OWKUalVZH6BTk0bHA8BDUJBhIboA8SG6Se5N773nstX6//rH3ufeee040arR7Zs06e6/9+H3X7/ld6whH4Fh69VfYdPvl+e+r1swFTjGzS4D3AQI8IMLdEnl245evHAQYTr9Ib/aJ3/jbwhE6TrpqzTwRWQ2cDUxvv8PIHAf//qHqQx/56dgVwif3HInvul/nof5r1k7+fdbSa9Z+1zm3W8StEOemi3OI80VzeROHej/9j3bouWM95d0j026+/0DXzWc133Ow66bfrQb6r1k7H5FHgKUikr9KpPXNNlkBxsJR5cHvjRLUsGBoNDTYJo367unV63f9OnIkhyXs1WtBhI23XUr/ynX9wGdE5EMgiAgmeS/QCmLCejCM/lFDuhOSaBANjUrMbKlmsnMkufkbmvG5GbWPbzxQuQmLdlg+4n6Zc45LgHb1r1y3BmSDOP8hxCHeg/M4X5jL5N63nuM8y8YEuhKkK0G6PL6SkHZ7km5PWvF/5kuy4WDXTWs0apdmAYBhvvirA1h61RoANt1+OSddtWYJIl9D3B4Rd7nzuU03hXbe4ZogfIJLEpyf3HIAlia8aVSg5KDsoJLkYCoJScWTVDxpxePL7nKfuj14/7VBPr+kl1wLO/mnw/OBE69di2Rhrog7HuGzIu4DOIcgiHMgMu6c+W+Xv6R5jhRvneQEZtTFePrhEbqDgeYmlDfN+0yxeiA0lNhQQjWS1ZWg8QcB+4eAbh6FwX4+3Q7ghI+t+oAgZ+HkWEHehHPzBJnTjCDjQktx7prnBQARrABJ4Q8TvmsoxjFjyn/86GD+RTVQhdAKIAehxEYg1JRQi2S1SGZKhu5tEPcE7IUMHTDskTfyuR/ICVfefoOI/DOSC9Lsm8IHNRQ3EQ69J/GeNE2gCI/4vG8+Vw86oVszMmDlq3U+NlADmzL7QaERoRZyYN5jYxlhqE5oKCGDrBHJiDRQsqIFFMU+mSDyKaRQu0j+sxBWDa7741M5bclRqOUKEwc/2vQaa594lcQ78B7n/LhWgipfu+TtBNWm/Fjqmf+PD0M5yc0qNGe90MYfHAfnL4Xl88ALYpDsHsWtfxFufBIbMjQzPIYiRASHoNinEkFqINOF3FQQV1hWHh5PP3EhJx8zp8Xu+ro9X/r2I8xZvAyXNCORA3GcMLubkxf0tjnbT2ZUsTDMoml94GM+629bBFe+BRa2J25ZPBN//dsYOWU6Y2d/nV6ZgRbm6BE0B1F1CLuk0MCE6eS9955plfZUsahvNiUi9T2v4EplfClFkhI+TVm+YGbHaFGe18vm2uvsCPsh9fC2hfC5d3UUfvKx76GNbKwMUkszPILH4QoNOGSXA9nedDxpzr7ks1lKPan3HV989ltOIquNUt21FVcIL6USS+d3Fqg8dzou9fy8uosd8wN89szDyrQHntqCr3h+nGxn2NUKEDkAgdcSRAbGhYZ89kUQJyRJktt5h+P9bz2R//7ZK8T6GNVdW+g5th9zwpI53R3vT+f0QJrnj/RPTm5P1llk/xMvMfTES/hKyqwzTqRyzBzCcBWXODRGNiS7OLmxgBTf1MBAIvDz8ajX1EARXUppQnoIAKedsJC0lCeqUBtlbPtLdC1ezpJZlY73l+ZMw7wgpYQZ/Ue3jT93xVoOPrctj0yZsvWWByjPmk62bxRxgnMO54wX/HaOj310U8YhLznEbcqFLiJQMxk5R5r4QwLoqZSY29tTOHBCVh3B79nCzErn8qrU2wOJh5JQnttqZkPPbWXoxwNI2SOpR0oJrpySHRjD1HBOwJH3AhvYyQg1EtzGRER2IhIF8eO5oACTen9IE6qUEubMmMZQLSDOEQ3evXj2IW25NGsa5sGVS21jcSxDUpdnc2d5kyIp+jwaOieoy03ciWOjvR4rJLscsBeoNjOPTXLoNG3VwPBobaKMdY4lR83CJNdWUON9Jx83Pj54sNrqA73d4AQ1bQMw54wT6Vo4G5yMlyTjDYoJnah4c4msOkJ9rzMYFJHqeBht1vYIaeJJ/ERZsHnXvpYPn3nS0WR5hqOUON66uG987NltrYTLl1Mk8SDC2I79bSBOufMyXFc6UeDIRLk5mW5IYUYCVYNB9+KqK6rAtqKaz4u2An3qPW5SXfNSBwCNmM/ootnT8cW9ZsbLu4fahPTTShgw+PRL7WF2fi9n/OAGFn7kdLQeJlVqwsScttSeAx/mrmphH3IfTTIy6Z7e7lZ73Xuwxmv7Doyfz+wus2BmTwGgh+YkBDW27x9pB9BVBgdb//1/CGP19uybepasfD/v+OHfUuqbMYnSSVvZLHDfOB8wsbunjqoZfdNbQ2JQ5ZGfvdJy7fdPXICacezc3vEJCqq8uu9gO/2rlMAMEXjmr79KrDY6J72+GZz2n9cx6+3HY4WGbco9it4N4PpXrmPTrZftBQYmI1CDeTNaATRC5KGfbm25dvrxCwhRWbZwIgLtHBpl59BoBwBpIYlQHzzA0yvvorFvpCMIP63M8tWX0LVoNmaWP2fjMLZeyF371nMZbuOtlzZl/uZkAq5mzOtpBVDPAi8M7G65dsL8mYgIy94wAeDBn2yjGmK7UKU0r0Q1JzX13cM8ddmdvHrfjzrTxXLC8jsvJgxXMbO8ss2DxjcBzmdtbkLLrr0LkAfIuXeuIjPmTTGhsVpGUGXb4PD4tVnTypQSz/HzJ4q47z+/lVkdbDwppa0sTEGrDV5e9SDPX3MPWQdtTFu2kDnvWZ4vDFgR6U0e/I5cPsGJN/zLJcQYH8fMDMtZlCp9U0zoYK2OqbLl9aFJjl6mf8Gs8fOReoOte4Y5aW8HJy6nBYlpgsiBuDRh+NkBnjr3FrIOz80//1RMm3KZRYuPrbCvtJL6F2+7NANuaZqZRmVuT1fLi6q1BlGNn746YUblxPPu/kXj58+/Moh3wuL9HXygXMqpY4wTpKYJRI1YbbBtzcNtz3UdNxdD0Ghg3Hwea0PHVYlQr38CUzAlmjFvRnmKCdVBlSc3b2+5/tF39LcAKIkweyzDgk4BUGigUWghxEkaycGMbNjRHl4Tn/uAGg3lbzouqyz7q3t48V+vMODrZiCqdKWthdlorYFZ5OkpAMrpBGfYsGMv3mBONSNMKSd8pVQIr7nwwYo2oYV0Zns53tg3gjYUM/u3C2y13e+vbAew4ZaLWX7dvaB6K6bMaKb1ySZUrWNRqdUbPLel80rghh37OHqkRlc10Dg41u4DIVKa0Z3z6CxCI0CIWBZxacLRHz2jnZU9vhkNiiq33u+v5INxdeelxZ996SKAJ5d//KvfmdldWjH1RaPVGmgkEeF7z7zIKb93VGumHqmxde8Q73n9IBqVMFxtMyHJjDff/hegRm3HEKObdxJGanQtnMOMNx9LpQMlHbjjEaLa+g/G1U8d1tpoIwt/PrenvBto8eLRsRoWlcQl/PCFl/nMhe9qee57z2zGzHjLroNosDYAvlKCoFTm94IIlQWzmHnq4l9IKTdc+w2yoVqVxF10WEuLy6+7l823XTJy9hsXfXnq2Fi1ioYIGhgZGWPfSKuA335iAwuqDaaPZpApYUo2dqWErqNmdl4A7nC8/p1nGVjzGJa4O84Jq0cn2/4hARRmxF++900fB7a0mlAdNKIhMFqttfADNePlHYMs3l9FC8ds00B3iWmTSu5DHfVdw2z65HqeOm8VGvTlc8Lq64EW2/+FJmRmiAg/2fLa2dsHhzeoagURLCqqAYcnqxvn/N06vM+XHE2EGJXj9lfRTBGF4WcGKPf15qUDRm37fvZ8/3kOPLONN5x3KrPOPInu4/ty+rhvhKEntvDauscZfPTnxLoipVJNI+8BmOq8v3SDowmi571XXd3TXblNxNFdKeeMzTmcKyiguIJk5P21LwyzbCiAgAXFQsxrgKK2d6UEoqL1gDViPq4QGzGvdSRfEQyZopGrz9XVq+53V/JBXf2r7Q+ICMddeAMj/7Xq9kqa3F5OE1RzYUwjGhWLEYsh70MghMCioUYeHjPN6V/i8yV353Hi8rFgOHH5WFoqyH4J8x6NEDNFo916rq5e9V13xSGFP6wtpuMuvIEQgvfe/1CcO3OcdrqJheB8IQx6G8Ydjw5TS/JVBGndpAEFyesZLOaZVaM2t5rQoMRoxGiPBmv8YepK8Vxd85tt8g188/N47+O2b33hnab6pKmOC0CMmOaaCKqc9lqNRiOijYjVFa0r2sh7q0diPZIVfWgUra7EuhIakSwzQtAnVtiaszy/XPjD3iObpLAzzfQxzN5O4bhiERCCE07bOkY9ixDHiffE7Bf7ZHmplfca86pX1VCFaPq/oO9qcq4jts267VtfaAbLbNu3bnwH2HrLJcg1YEpXLTJ/sEGjrmT1SKgpWV3JGkqYdC3U4vj1LIuEYGTRCKbrL2Dt6YLLAM5j7W9hn9iagG68ANVrc5akmCp9wxlZpnlraL4pUZ/UGk2hlRCULESiKpkpEV15IWsvyOfdfnsb3dvW3wjAsed9gm3f/uKtWFyB2m4s0jecETTmLUayGAkxFzZEza+pEiwXOuQ7La8reu6fsu62+8ip7YWs+91sdB+z4vqmWXVFcY+veH70rWe8XJ9YW+rwTHN2LWeuTwPvFKgCfJi7/3//K/GlnkvPnzcS7wTmyiFfbRgMgnzso9y9/kh894gBaB73cNEqgYuBaVOGRoB7LuLeq4/k99wRFByAi7n3qogtjdinI7YvYnuL3/1N4e/loiMG4P8A+S8sURAD73YAAAAASUVORK5CYII=') left center no-repeat;
23)     min-height: 48px;
24) }
25) 
#0 /vendor/magento/framework/View/Asset/PreProcessor/AlternativeSource.php(155): Magento\Framework\Css\PreProcessor\Adapter\Less\Processor->processContent(Object(Magento\Framework\View\Asset\File))
#1 /vendor/magento/framework/View/Asset/PreProcessor/AlternativeSource.php(115): Magento\Framework\View\Asset\PreProcessor\AlternativeSource->processContent('css/styles.css', '', '', Object(Magento\Framework\View\Asset\File\FallbackContext))
#2 /vendor/magento/module-developer/Model/View/Asset/PreProcessor/PreprocessorStrategy.php(76): Magento\Framework\View\Asset\PreProcessor\AlternativeSource->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#3 /vendor/magento/framework/View/Asset/PreProcessor/Pool.php(77): Magento\Developer\Model\View\Asset\PreProcessor\PreprocessorStrategy->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#4 /vendor/magento/framework/View/Asset/Source.php(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#5 /vendor/magento/framework/View/Asset/Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#6 /vendor/magento/framework/View/Asset/File.php(157): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#7 /vendor/magento/framework/App/StaticResource.php(121): Magento\Framework\View\Asset\File->getSourceFile()
#8 /vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\StaticResource->launch()
#9 /pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#10 {main}
```

As a quick (temporary) solution for us was to make this file empty:
`vendor/msp/security-suite-common/view/adminhtml/web/css/source/_module.less`

We think Magento parse wrong data:image/png;base64 in your file, maybe you can replace background data/image with the regular image?
